server:
  port: 7801

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: hello-service-hystrix

logging:
  config: classpath:logback.xml
