server:
  port: 8080

mybatis-plus:
  mapper-locations: classpath*:mappers/*Mapper.xml
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true

spring:
  application:
    name: zuul-gataway
  datasource:
    url: jdbc:mysql://47.108.82.29:3306/meetingfilm?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: yasin
    password: Password@123
    filters: log4j,wall,mergeStat

logging:
  config: classpath:logback.xml

eureka:
  client:
    service-url:
      defaultZone: http://yasin:yasin123@localhost:8761/eureka/

zuul:
  prefix: "/meetingfilm/"
  routes:
    meetingfilm-user:
      path: /userapi/**
      serviceId: user-service
      retryable: true
    meetingfilm-cinema:
      path: /cinemaapi/**
      serviceId: cinema-service
      retryable: true
    meetingfilm-film:
      path: /filmapi/**
      serviceId: film-service
      retryable: true
    meetingfilm-hall:
      path: /hallapi/**
      serviceId: hall-service
      retryable: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 20000
