server:
  port: 7658

eureka:
  client:
    service-url:
      defaultZone: http://yasin:yasin123@localhost:8761/eureka/


spring:
  application:
    name: hello-service-provider

logging:
  config: classpath:logback.xml
