server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://yasin:yasin123@localhost:8761/eureka/

spring:
  application:
    name: test-service

logging:
  config: classpath:logback.xml
